name: AI Code Review

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ai-code-review-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  ai_review:
    name: Run AI code review
    # Triggered on the pull_request_target types above, including synchronize
    runs-on: ubuntu-latest
    steps:
      # CHOOSE ONE reviewer action. Example: CodiumAI PR-Agent
      - name: AI PR review
        uses: CodiumAI/PR-Agent@v0.9.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
        # Alternatively, if your chosen action uses different inputs:
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   openai_api_key: ${{ secrets.OPENAI_API_KEY }}

