name: Bedrock AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  bedrock-ai-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository (the PR repo)
        uses: actions/checkout@v4

      - name: Checkout planto-reviewer (private repo with action)
        uses: actions/checkout@v4
        with:
          repository: coding-jr/planto-reviewer
          # path to place repo in workspace
          path: planto-reviewer
          # token with read access to the private repo (store this as a secret)
          token: ${{ secrets.PLANTO_PAT }}

      - name: Run AI Code Review (local action from planto repo)
        # point to the action folder inside the checkout above
        uses: ./planto-reviewer/.github/actions/auto-reviewer
        env:
          NODE_OPTIONS: "--experimental-fetch"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          model_temperature: 0
          model_name: "gpt-4"
          exclude_files: "*.js, *.json, *.md, *.yml, *.js.map, .node-version"
